'''
    Configuration parameters for the USV vision-based control system.
'''

import os
import numpy as np

# =========================================================
# UDP / TCP settings
# =========================================================
UDP_IP = "127.0.0.1"

# (Follower_Left)
PORT_LEFT_RX = 5066
PORT_LEFT_TX = 5065

# (Follower_Right)
PORT_RIGHT_RX = 5068
PORT_RIGHT_TX = 5067

HOST = "0.0.0.0"
PORT_LEFT_FRONT_CAM = 9998
PORT_RIGHT_FRONT_CAM = 9999
PORT_LEFT_SIDE_CAM = 10000
PORT_RIGHT_SIDE_CAM = 10001

BOAT_SIDES = ("Left", "Right")
CAMERA_STREAMS = {
    "LeftFront": {
        "boat": "Left",
        "role": "front",
        "port": PORT_LEFT_FRONT_CAM,
        "window": "Left Front Camera",
        "search_dir": 1.0,
    },
    "LeftSide": {
        "boat": "Left",
        "role": "side",
        "port": PORT_LEFT_SIDE_CAM,
        "window": "Left Side Camera",
        "search_dir": 1.0,
    },
    "RightFront": {
        "boat": "Right",
        "role": "front",
        "port": PORT_RIGHT_FRONT_CAM,
        "window": "Right Front Camera",
        "search_dir": -1.0,
    },
    "RightSide": {
        "boat": "Right",
        "role": "side",
        "port": PORT_RIGHT_SIDE_CAM,
        "window": "Right Side Camera",
        "search_dir": -1.0,
    },
}
FRONT_STREAM_BY_BOAT = {"Left": "LeftFront", "Right": "RightFront"}
SIDE_STREAM_BY_BOAT = {"Left": "LeftSide", "Right": "RightSide"}

# =========================================================
# Vision / display / model
# =========================================================
SHOW_WINDOW = True
SHOW_OVERLAY_TEXT = True
DISPLAY_UPDATE_INTERVAL_SEC = 0.0
YOLO_MODEL_PATH = "../best_v2.pt"
USE_DEPTH_ANYTHING_TEST = False
DEPTH_ANYTHING_MODEL_ID = "LiheYoung/depth-anything-small-hf"
DEPTH_ANYTHING_DEVICE = "cuda"
DEPTH_OVERLAY_SCALE = 0.30
DEPTH_INPUT_MAX_SIZE = 256
DEPTH_UPDATE_INTERVAL_SEC = 0.30
DEPTH_ONLY_ON_YOLO = True
TCP_FRAME_TIMEOUT = 1.0
MAX_JPEG_BYTES = 8 * 1024 * 1024
WINDOW_SIZE = (640, 360)
YOLO_CLASS_LEADER = 0
YOLO_CLASS_FOLLOWER = 1
YOLO_CLASSES = [YOLO_CLASS_LEADER, YOLO_CLASS_FOLLOWER]
YOLO_CONFIDENCE = 0.12
YOLO_MIN_BOX_AREA = 300
YOLO_DEVICE = "cuda:0"
YOLO_USE_BATCHING = True
YOLO_IMGSZ = 640
YOLO_BATCH_WAIT_SEC = 0.008
YOLO_ENABLE_WARMUP = True
YOLO_ENABLE_TORCH_COMPILE = False
ENABLE_WAKE_DETECTION = False
VISION_CPU_THREADS = max(1, min(8, (os.cpu_count() or 4)))
IGNORE_TOP_RATIO = 0.25
IGNORE_BOTTOM_RATIO = 0.18

# Wake detection
WAKE_LOWER_WHITE = np.array([0, 0, 220], dtype=np.uint8)
WAKE_UPPER_WHITE = np.array([180, 55, 255], dtype=np.uint8)
WAKE_SKY_CROP_RATIO = 0.50
WAKE_BOAT_CROP_RATIO = 0.90
WAKE_MASK_PREVIEW_SCALE = 0.30
WAKE_IGNORE_BOTTOM_RATIO = 0.12
WAKE_MIN_BBOX_HEIGHT = 14
WAKE_MIN_BBOX_WIDTH = 8
WAKE_MIN_ASPECT_RATIO = 1.25
WAKE_MIN_FILL_RATIO = 0.16
WAKE_MAX_CENTER_OFFSET = 0.42
WAKE_MAX_OFFSET_FROM_TRACK = 0.18
WAKE_MAX_OFFSET_FROM_YOLO = 0.12
WAKE_MAX_TOP_GAP_FROM_YOLO_RATIO = 0.14
WAKE_OPEN_KERNEL = (3, 3)
WAKE_CLOSE_KERNEL = (21, 5)
WAKE_DILATE_KERNEL = (5, 3)

# Tracking / prediction
TRACK_HOLD_SEC = 0.60
TRACK_REACQUIRE_BIAS = 0.35
TRACK_OFFSET_ALPHA = 0.35
TRACK_AREA_ALPHA = 0.25
STALE_TARGET_THROTTLE_SCALE = 0.65
STALE_TARGET_STEER_SCALE = 0.85
SEARCH_FORWARD_THROTTLE = 0.24
SEARCH_STEER_GAIN = 0.85
DISABLE_SEARCH_MODE = True
VISUAL_FAR_BOOST_MAX = 0.16
VISUAL_SHRINK_BOOST_MAX = 0.08
VISUAL_FAR_BOOST_EXPONENT = 1.35
FOLLOW_FAR_MAX_THROTTLE = 0.9
PREDICTION_HORIZON_SEC = 0.40
PREDICTION_OFFSET_BLEND = 0.55
PREDICTION_AREA_BLEND = 0.35
PREDICTION_VELOCITY_ALPHA = 0.35
PREDICTION_STALE_DECAY = 0.88
PREDICTION_MAX_OFFSET_DELTA = 0.35
PREDICTION_MAX_AREA_DELTA_RATIO = 0.45
PREDICTION_IDLE_DECAY = 0.60
PREDICTION_MIN_OFFSET_STEP = 0.012
PREDICTION_MIN_VERTICAL_STEP = 0.010
PREDICTION_MIN_AREA_RATIO_STEP = 0.045
PREDICTION_CONTROL_MIN_CONF = 0.32

FRONT_PRIORITY_CONFIDENCE = 0.35
FRONT_PRIORITY_STALE_SCALE = 0.25
FRONT_PRIORITY_NO_FRONT_STEER_SCALE = 0.20

SIDE_TRACK_STEER_KP = 0.62
SIDE_TRACK_MAX_STEER_BIAS = 0.14
SIDE_TRACK_MAX_THROTTLE_BIAS = 0.14
SIDE_TRACK_AREA_GAIN = 0.18
SIDE_STEER_DEADZONE_H = 0.05
SIDE_STALE_BIAS_SCALE = 0.72
YOLO_TRACK_STEER_GAIN = 0.92
YOLO_TRACK_THROTTLE_GAIN = 1.08
WAKE_TRACK_STEER_GAIN = 0.90
WAKE_TRACK_THROTTLE_GAIN = 0.82
WAKE_TRACK_AREA_BIAS = 0.88
FOLLOWER_TRACK_STEER_GAIN = 0.70
FOLLOWER_TRACK_THROTTLE_GAIN = 0.90
FOLLOWER_TRACK_AREA_BIAS = 0.84
FOLLOWER_MOTION_MIN_CONF = 0.10
FOLLOWER_MOTION_STEER_GAIN = 0.42
FOLLOWER_MOTION_MAX_STEER = 0.24
FOLLOWER_AREA_CATCHUP_MAX = 0.04
STALE_TRACK_STEER_GAIN = 0.80
STALE_TRACK_THROTTLE_GAIN = 0.80
VISION_FRONT_TARGET_OFFSET = 0.0
VISION_SIDE_TARGET_OFFSET = 0.0
VISION_AREA_ERROR_DEADZONE_RATIO = 0.06
VISION_FRONT_AREA_TOLERANCE_RATIO = 0.10
VISION_SIDE_AREA_TOLERANCE_RATIO = 0.12
VISION_FRONT_AREA_GAIN = 0.72
VISION_FRONT_AREA_MIN_THROTTLE = 0.08
VISION_FRONT_CRUISE_THROTTLE = 0.18
VISION_FRONT_CRUISE_STEER_LIMIT = 0.055
VISION_FRONT_CRUISE_MAX_POSITIVE_RATIO = 0.20
VISION_FRONT_CRUISE_MAX_NEGATIVE_RATIO = 0.06
VISION_TURN_CATCHUP_GAIN = 0.16
VISION_TURN_CATCHUP_MAX = 0.18
VISION_TURN_SPEED_CEILING = 0.82
VISION_TURN_SLOWDOWN_START = 0.55
VISION_TURN_SLOWDOWN_MIN_SCALE = 0.78
VISION_TURN_FORMATION_AREA_BOOST = 0.18
VISION_TURN_FORMATION_STEER_BOOST = 0.08
VISION_TURN_FORMATION_THROTTLE_SCALE = 0.88
FOLLOWER_PAIR_AREA_BALANCE_TOLERANCE_RATIO = 0.08
FOLLOWER_PAIR_CATCHUP_GAIN = 0.22
FOLLOWER_PAIR_CATCHUP_MAX = 0.18

# =========================================================
# Controller params
# =========================================================
KV_STEER = 1.02
STEER_DEADZONE_H = 0.06
FINAL_STEER_DEADZONE_H = 0.045
STEER_SLEW_RATE_PER_SEC = 2.4
SEARCH_MODE_STEER = 0.5
KV_THROTTLE_P = 0.00018
FOLLOW_BASE_THROTTLE = 0.40
FOLLOW_MAX_THROTTLE = 0.62

# Area thresholds
YOLO_AREA_OPT = 250000
YOLO_AREA_MIN = 200
YOLO_AREA_MAX = 350000
FOLLOWER_AREA_OPT = 150000
FOLLOWER_AREA_MIN = 200
FOLLOWER_AREA_MAX = 260000

WAKE_AREA_OPT = 2000
WAKE_AREA_MIN = 650
WAKE_AREA_MAX = 5000
MIN_WAKE_CONTOUR = 220
FUSION_YOLO_OFFSET_WEIGHT = 0.78
FUSION_WAKE_OFFSET_WEIGHT = 0.26
FUSION_MAX_OFFSET_GAP = 0.45
FUSION_MIN_WAKE_WEIGHT = 0.08
PREDICTION_ARROW_MIN_CONF = 0.12
PREDICTION_ARROW_PIXELS = 90
PREDICTION_ARROW_MIN_PIXELS = 18
SIDE_TRACK_STEER_SIGN_BY_BOAT = {"Left": 1.0, "Right": 1.0}

# Camera shake
ENABLE_CAMERA_SHAKE = True
CAMERA_SHAKE_SPEED_GAIN = 8.0
CAMERA_WAVE_FREQ = 0.6
CAMERA_WAVE_AMP_BASE = 3.0
CAMERA_WAVE_AMP_SPEED_GAIN = 5.0
